# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldp',
            name='site',
            field=models.CharField(default='University Hospital Southampton  NHS FT', max_length=100),
            preserve_default=False,
        ),
    ]
