# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmcapp', '0002_ldp_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmc',
            old_name='name',
            new_name='gmc_name',
        ),
        migrations.RenameField(
            model_name='ldp',
            old_name='name',
            new_name='ldp_code',
        ),
        migrations.RenameField(
            model_name='ldp',
            old_name='site',
            new_name='site_name',
        ),
        migrations.RenameField(
            model_name='ods',
            old_name='name',
            new_name='ods_code',
        ),
    ]
