# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmcapp', '0003_auto_20170711_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmc',
            name='ldps',
        ),
    ]
